server:
  port: 8888

spring:
  application:
    name: config-server
  security:
    basic:
      enabled: true
    user:
      name: configuser
      password: configPass$1234
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - http://localhost:29092
          bindings:
            springCloudBusOutput:
              destination: springCloudBusTopic
            springCloudBusInput:
              destination: springCloudBusTopic
    bus:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/halilm00/config-repo
          force-pull: true # pull the latest code from GIT in case the local repo has some issues and couldn't able to update the repo
          refresh-rate: 3
          skipSslValidation: true # Git Server SSL validation can be disabled
          timeout: 10 #HTTP connection timeout (in seconds)
  kafka:
    bootstrap-servers:
      - http://localhost:29092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
register-with-eureka: true # By default, this is true

management:
  endpoints:
    web:
      exposure:
        include: "*"