server:
  port: 8888
spring:
  application:
    name: config-server
  security:
    basic:
      enabled: true
    user:
      name: configuser
      password: configPass$1234
  cloud:
    config:
      server:
        git:
          uri: https://github.com/halilm00/config-repo
          force-pull: true # pull the latest code from GIT in case the local repo has some issues and couldn't able to update the repo
          skipSslValidation: true # Git Server SSL validation can be disabled
          timeout: 10 #HTTP connection timeout (in seconds)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
register-with-eureka: true # By default, this is true